name: SCPRPSystem
main: cz.vojtiisek.scprpsystem.SCPRP
version: 1.0.0
author: Vojtiisek
load: POSTWORLD
softdepend: [Multiverse-Core]

commands:
    test:
    breach:
    arrest:
    revive:
    dcbreach:
    dcendbreach:
    frisk:
    unarrest:
    tests:
    level:
    designation:
    hire:
    scp:
    constructions:
    consoleaddxp:
    payout:
    consolepayout:
    cell:
    naufix:
    storage:
    dc:
    consoledesigrb:
    id:
    testworld:
    network:
    payoutxp:
    jail:
    unjail:
    food:
    arrived:
    daily:
    linkaccount:
    clear:
    tc:
    testchat:
    dropitems:
    findclassd: 
    mine:
    areadetector: